import { writable } from 'svelte/store';
import { db } from '$lib/api/tauri';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type LoadMode = 'chain' | 'per_endpoint';

export interface LoadFileUpload {
  /** Variable name the file's base64 contents will be bound to (so step
   *  bodies can reference `{{varName}}`). */
  variableName: string;
  /** Absolute path on disk; resolved at compile-time via `fileOps.readFileBase64`. */
  path: string;
  /** Whether the resolved value should be base64-encoded bytes (true) or
   *  decoded UTF-8 text (false). Defaults to text. */
  asBase64: boolean;
}

export interface LoadDataFile {
  /** Path to a CSV or JSON file. CSV: first row is header; JSON: must be
   *  an array of objects with string keys. Parsed into `dataRows` at
   *  compile-time. */
  path: string;
  format: 'csv' | 'json';
}

export interface LoadEnvFile {
  /** Path to a flat JSON file `{ key: value, ... }`; merged into initialVars
   *  at compile-time. */
  path: string;
}

export interface LoadConfig {
  collectionId: number | null;
  mode: LoadMode;
  /** Number of parallel virtual users / workers. */
  concurrency: number;
  /** Run duration in seconds. If both this and `totalRequests` are set, the
   *  run stops on whichever is reached first. */
  durationSecs: number;
  /** Total request cap (optional). 0 = no cap. */
  totalRequests: number;
  /** Ramp-up window in seconds (spread VU spawns over this window). 0 = all at once. */
  rampUpSecs: number;
  /** Target requests-per-second cap. 0 = uncapped. */
  targetRps: number;
  /** Per-request timeout in seconds. */
  timeoutSecs: number;
  /** Optional free-form context the user wants the AI to weigh when drafting
   *  the plan (e.g. "use {{access_token}} for everything after /auth/login"). */
  notes: string;
  /** Files to upload / pre-load into initialVars. */
  uploadFiles: LoadFileUpload[];
  /** Optional data file for per-iteration variation. */
  dataFile: LoadDataFile | null;
  /** Optional env file merged into initialVars. */
  envFile: LoadEnvFile | null;
}

export interface PlanExtraction {
  jsonPath: string;
  variableName: string;
}

export interface PlanStep {
  /** Stable id used to correlate samples back to a step (we generate this
   *  from the source request id + position; the Rust side echoes it back). */
  id: string;
  /** Optional: link back to the saved request for setup/dedup. */
  sourceRequestId?: number;
  name: string;
  method: string;
  url: string;
  headers: Record<string, string>;
  body?: string;
  /** When true, the Rust worker base64-decodes `body` before sending. Used
   *  for file uploads. */
  bodyIsBase64?: boolean;
  /** JSON-path extractions applied to each response in chain mode. The
   *  worker updates its local vars map with the extracted values so later
   *  steps in the same iteration can reference them via `{{varName}}`. */
  extractions: PlanExtraction[];
}

export interface DraftPlan {
  mode: LoadMode;
  concurrency: number;
  durationSecs: number;
  totalRequests: number;
  rampUpSecs: number;
  targetRps: number;
  timeoutSecs: number;
  /** Variables that should be set before any worker starts (tokens, env). */
  initialVars: Record<string, string>;
  steps: PlanStep[];
  /** AI-supplied summary of WHY it ordered things this way / which vars
   *  were detected as tokens. Shown verbatim in the review step. */
  rationale: string;
  /** Whether the plan was generated by the AI or by the metrics-only
   *  fallback. The review step shows a small note in the fallback case. */
  origin: 'ai' | 'fallback';
}

// ---------------------------------------------------------------------------
// Live metrics shapes (must match Rust ProgressEvent / DoneEvent verbatim)
// ---------------------------------------------------------------------------

export interface StepAggregate {
  step_id: string;
  name: string;
  method: string;
  url: string;
  count: number;
  errors: number;
  error_rate: number;
  bytes: number;
  min_ms: number;
  max_ms: number;
  avg_ms: number;
  p50_ms: number;
  p90_ms: number;
  p95_ms: number;
  p99_ms: number;
  status_codes: Record<string, number>;
}

export interface ProgressEvent {
  elapsed_ms: number;
  duration_ms: number | null;
  active_workers: number;
  requests_total: number;
  requests_ok: number;
  requests_err: number;
  rps_rolling: number;
  p95_rolling_ms: number;
  per_step: StepAggregate[];
  throughput_series: number[];
}

export interface DoneEvent {
  elapsed_ms: number;
  total_count: number;
  total_ok: number;
  total_err: number;
  bytes_total: number;
  rps_overall: number;
  per_step: StepAggregate[];
  bottlenecks: string[];
  throughput_series: number[];
  cancelled: boolean;
}

export type RunPhase = 'configure' | 'review' | 'running' | 'results';

// ---------------------------------------------------------------------------
// Defaults
// ---------------------------------------------------------------------------

export function defaultConfig(collectionId: number | null = null): LoadConfig {
  return {
    collectionId,
    mode: 'chain',
    concurrency: 10,
    durationSecs: 30,
    totalRequests: 0,
    rampUpSecs: 0,
    targetRps: 0,
    timeoutSecs: 30,
    notes: '',
    uploadFiles: [],
    dataFile: null,
    envFile: null,
  };
}

// ---------------------------------------------------------------------------
// Stores (in-memory; the LoadTestScreen drives lifecycle)
// ---------------------------------------------------------------------------

export const phase = writable<RunPhase>('configure');
export const config = writable<LoadConfig>(defaultConfig());
export const draftPlan = writable<DraftPlan | null>(null);
export const planLoading = writable<boolean>(false);
export const planError = writable<string | null>(null);
export const liveProgress = writable<ProgressEvent | null>(null);
export const finalResult = writable<DoneEvent | null>(null);
export const aiAnalysis = writable<string>('');
export const aiAnalysisLoading = writable<boolean>(false);
export const runError = writable<string | null>(null);

export function resetForNewRun(keepConfig = true) {
  if (!keepConfig) config.set(defaultConfig());
  draftPlan.set(null);
  planLoading.set(false);
  planError.set(null);
  liveProgress.set(null);
  finalResult.set(null);
  aiAnalysis.set('');
  aiAnalysisLoading.set(false);
  runError.set(null);
  phase.set('configure');
}

// ---------------------------------------------------------------------------
// Per-collection config persistence (mirrors chainRunner's `chains_{id}` key)
// ---------------------------------------------------------------------------

const SETTINGS_KEY = (id: number) => `loadtest_${id}`;

/** Restore the last-used config for a collection. Returns null if no
 *  previous config was saved. Silently swallows DB errors so the screen
 *  can fall back to defaults. */
export async function loadConfigFor(collectionId: number): Promise<LoadConfig | null> {
  try {
    const raw = await db.getSetting(SETTINGS_KEY(collectionId), '');
    const text = typeof raw === 'string' ? raw : '';
    if (!text) return null;
    const parsed = JSON.parse(text) as Partial<LoadConfig>;
    const base = defaultConfig(collectionId);
    const merged = { ...base, ...parsed, collectionId };
    // A persisted config may carry null/undefined/non-numeric values for the
    // numeric knobs (older saves, partial writes). Spreading those over the
    // defaults blanks the GUI inputs, so coerce each one back to a finite
    // number, falling back to the default when the saved value is unusable.
    const num = (v: unknown, fallback: number) =>
      typeof v === 'number' && Number.isFinite(v) ? v : fallback;
    merged.concurrency = num(merged.concurrency, base.concurrency);
    merged.durationSecs = num(merged.durationSecs, base.durationSecs);
    merged.totalRequests = num(merged.totalRequests, base.totalRequests);
    merged.rampUpSecs = num(merged.rampUpSecs, base.rampUpSecs);
    merged.targetRps = num(merged.targetRps, base.targetRps);
    merged.timeoutSecs = num(merged.timeoutSecs, base.timeoutSecs);
    return merged;
  } catch {
    return null;
  }
}

export async function saveConfigFor(collectionId: number, cfg: LoadConfig): Promise<void> {
  try {
    await db.setSetting(SETTINGS_KEY(collectionId), JSON.stringify(cfg));
  } catch {
    /* non-fatal */
  }
}
